name: "Install Dependencies"
description: "Installs project dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install
      shell: bash